<a href="https://colab.research.google.com/github/RaffyJO/machine-learning-2024/blob/main/ML-Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nama: Raffy Jamil Octavialdy
<br>
Kelas: TI - 3D
<br>
NIM: 2241720082**

**Kode 1-1 merupakan implementasi normalisasi berdasarkan Persamaan 1.**

In [ ]:
def norm_data(data):
  '''
  Melakukan normalisasi data.

  Parameter:_
    data (list) : Data yang akan dinormalisasi

  Returns:
    data (list) : Data hasil normalisasi
  '''

  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)

  return data

# contoh penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data) # melakukan normalisasi
print(n_data)

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


**Kode 1-2 merupakan implementasi normalisasi dengan menggunakan library Scikit-learn untuk kasus data fitur dalam bentuk 2 dimensi
(2d list atau 2d array).**

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6) # bulatkan 4 angka koma
np.set_printoptions(suppress=True) # hilangkan nilai e

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input dalam bentkan n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003],
]

# Ubah ke bentuk numpy n-dimensional array
data = np.array(data)
print('Data Asli')
print(data)

# Mendefinisikan obyek MinMaxScaler
scaler = MinMaxScaler()
# Transformasikan data
scaled = scaler.fit_transform(data) # Fungsi normalisasi pada library Scikit-learn berasal dari kelas ‘MinMaxScaler’
print('Data Normalisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


**Implementasi Standarisasi**
<br>
Kode 1-3 merupakan implementasi standarisasi dengan menggunakan library Scikit-learn. Pada Scikit-learn, standarisasi dapat dilakukan dengan menggunakan kelas ‘StandardScaler’.

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6) # bulatkan 4 angka koma
np.set_printoptions(suppress=True) # hilangkan nilai e

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input dalam bentkan n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003],
]

# Ubah ke bentuk numpy n-dimensional array
print(data)
data = np.array(data)
print('Data Asli')
print(data)

# Mendefinisikan obyek StandardScaler
scaler = StandardScaler()
# Transformasikan data
scaled = scaler.fit_transform(data) # Fungsi normalisasi pada library Scikit-learn berasal dari kelas ‘MinMaxScaler’
print('Data Standarisasi')
print(scaled)

[[100, 0.0001], [50, 0.05], [30, 0.003]]
Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


**Implementasi Ordinal Encoding**
<br>
Pada percobaan ini kita akan mencoba melakukan ordinal encoding dengan mengimport kelas ‘OrdinalEncoder’.

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Inisiasi obyek Ordinal Encoder
oe = OrdinalEncoder()

# Definisikan data dalam bentuk 2d
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

# Transformasi Ordinal Encoder
transform_oe = oe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


**Implementasi One-Hot Encoding**
<br>
Pada bagian ini, kita akan mempelajari bagaimana cara mengimplementasikan
one-hot encoding dengan menggunakan Scikit-learn kelas ‘OneHotEncoder’.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek One Hot Encoder
ohe = OneHotEncoder()

# Definisikan data dalam bentuk 2d
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

# Transformasi One Hot Encoder
transform_ohe = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoder')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoder
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


**Implementasi Dummy Variable Encoding**
<br>
Pada Scikit-learn, dummy variable encoding dapat dilakukan dengan menggunakan kelas yang sama dengan one-hot encoding yaitu dengan kelas ‘OneHotEncoding’. Namun, pada implementasi dummy variable encoding, perlu
di definisikan parameter ‘drop’ dengan nilai ‘first’.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek One Hot Encoder
ohe = OneHotEncoder(drop='first')

# Definisikan data dalam bentuk 2d
data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang'],
]

# Transformasi One Hot Encoder
transform_ohe = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoder')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoder
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


**Studi Kasus Ekstrasi Fitur dari Data Teks**
<br>
Data teks sering kali membutuhkan proses pra pengolahan data sebelum data tersebut dilatih dengan model pembelajaran mesin. Proses pra pengolahan data teks bertujuan untuk membuat dokumen masukan lebih konsisten dan mempermudah representasi teks. Pada pengolahan data teks secara umum berisi tiga proses utama yaitu tokenizing, stopword removal, dan stemming.

1. Siapkan data teks

In [ ]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story',
]

2. Lakukan pembobotan dengan menggunakan metode TF-IDF, digunakan konfigurasi ‘stopword’ dengan nilai ‘english’. Konfigurasi dilakukan karena kita menggunakan kata dalam bahasa inggris.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Inisiasi obyek TfidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil
print(resp)
print(resp.toarray())

# Kolom 1 merupakan indeks dari dokumen pada corpus.
# Kolom 2 merupakan indeks dari token yang terdapat dalam kalimat.
# Kolom 3 merupakan bobot dari TF-IDF hasil kalkukasi.

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.       0.      ]
 [0.       0.       0.       0.670092 0

3. Untuk mendapatkan token kata-kata yang didapatkan dari proses stopwords

In [ ]:
vect.get_feature_names_out()

array(['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse',
       'ran', 'saw', 'story', 'tiny'], dtype=object)

4. Pada proses ini, kita telah selesai melakukan ektraksi fitur teks yang hasilnya disimpan pada variabel ‘resp’.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story',
]

# Inisiasi obyek TfidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil
print('Hasil TF-IDF')
print(resp)

# Cetak token hasil stopword
print('Hasil Token')
print(vect.get_feature_names_out())

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
Hasil Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


**Tugas Praktikum**
1. Salin kalimat pada Kode 1-7 dengan tanda baca titik pada setiap kalimatnya dengan menggunakan editor teks.
2. Simpan kalimat tersebut pada file ‘.txt’ dengan nama ‘corpus.txt’.
3. Lakukan proses ektraksi fitur TF-IDF dengan menggunakan file ‘corpus.txt’.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Membaca file 'corpus.txt'
with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

# Inisiasi obyek TfidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Menampilkan hasil dalam bentuk dense array
print(resp.toarray())

# Menampilkan fitur-fitur yang diekstraksi
print(vect.get_feature_names_out())

[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.       0.      ]
 [0.       0.       0.       0.670092 0.       0.       0.       0.319302
  0.       0.       0.670092 0.      ]]
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


In [ ]:
!jupyter nbconvert --to html /content/ML-Week2.ipynbs